# Generated by Django 3.1.5 on 2021-01-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Код')),
                ('faculty', models.CharField(max_length=10, null=True, verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
                ('answer_tip', models.TextField(verbose_name='Примечания')),
                ('is_for_eng', models.BooleanField(default=False, verbose_name='Вопрос для Англ')),
                ('is_for_lec', models.BooleanField(default=False, verbose_name='Вопрос для Лектора')),
                ('is_for_pra', models.BooleanField(default=False, verbose_name='Вопрос для Практика')),
                ('is_two_answers', models.BooleanField(default=False, verbose_name='Разделять ответы для лектора и практика')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID ответившего')),
                ('teacher_type', models.CharField(choices=[('LECTOR', 'Лектор'), ('PRACTIC', 'Практик'), ('LECTOR_PRACTIC', 'Лектор и практик'), ('ENG', 'Английский')], default='LECTOR', max_length=20, verbose_name='Тип опросника')),
                ('continue_teach_answer', models.BooleanField(verbose_name='Ответ на продолжение преподавания')),
                ('open_question_answer', models.TextField(verbose_name='Ответ свободного микрофона')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('photo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка на фото')),
                ('is_eng', models.BooleanField(default=False, verbose_name='Это англ?')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherNGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ResultAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.PositiveSmallIntegerField()),
                ('answer_2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.result')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='teacher_n_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacherngroup'),
        ),
        migrations.AddField(
            model_name='group',
            name='teachers',
            field=models.ManyToManyField(through='mainapp.TeacherNGroup', to='mainapp.Teacher'),
        ),
    ]
