# Generated by Django 3.2.4 on 2021-07-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='univer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.university', verbose_name='Универ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='univer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.university', verbose_name='Универ'),
            preserve_default=False,
        ),
    ]
