# Generated by Django 3.1.5 on 2021-01-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='Факультет')),
            ],
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='locale',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Текста'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Результат опроса', 'verbose_name_plural': 'Результаты опроса'},
        ),
        migrations.AlterModelOptions(
            name='resultanswers',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопроссы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Препод', 'verbose_name_plural': 'Преподы'},
        ),
        migrations.AlterField(
            model_name='question',
            name='is_for_eng',
            field=models.BooleanField(default=False, verbose_name='для Англ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_for_lec',
            field=models.BooleanField(default=False, verbose_name='для Лектора'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_for_pra',
            field=models.BooleanField(default=False, verbose_name='для Практика'),
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty'),
        ),
    ]
