# Generated by Django 3.2.4 on 2021-06-21 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210620_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='cathedra',
        ),
        migrations.AddField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty', verbose_name='Факультет'),
        ),
    ]
