# Generated by Django 3.2.4 on 2021-07-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210717_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Последний законченный результат этого юзера по этому преподу', verbose_name='Актуальный результат'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Короткое название'),
        ),
    ]
