# Generated by Django 3.1.5 on 2021-01-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210127_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.PositiveSmallIntegerField(choices=[(5, '1-5'), (2, 'Нет/Да')], default=5, verbose_name='1-5 или нет/да'),
        ),
    ]
