# Generated by Django 3.1.5 on 2021-01-27 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_question_answer_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherngroup',
            unique_together={('teacher', 'group')},
        ),
    ]
