# Generated by Django 3.2.4 on 2021-07-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_result_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default=1, max_length=20, primary_key=True, serialize=False, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='№'),
        ),
        migrations.AddField(
            model_name='result',
            name='open_answer_moderate',
            field=models.BooleanField(null=True, verbose_name='Комментарий допущен?'),
        ),
        migrations.AlterField(
            model_name='resultanswers',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mainapp.result'),
        ),
        migrations.CreateModel(
            name='TeacherFacultyResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty', verbose_name='Факультет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher', verbose_name='Препод')),
            ],
            options={
                'unique_together': {('teacher', 'faculty')},
            },
        ),
    ]
