# Generated by Django 3.2.4 on 2021-06-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_result_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='date',
        ),
        migrations.AddField(
            model_name='result',
            name='time_finish',
            field=models.DateTimeField(default=None, null=True, verbose_name='Время окончания прохождения'),
        ),
        migrations.AddField(
            model_name='result',
            name='time_start',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='Время начала прохождения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='teacher_type',
            field=models.CharField(choices=[('LECTOR', 'Лектор'), ('PRACTIC', 'Практик'), ('LECTOR_PRACTIC', 'Лектор и практик'), ('ENG', 'Английский')], default='LECTOR', max_length=20, null=True, verbose_name='Тип опросника'),
        ),
    ]
