# Generated by Django 3.2.4 on 2021-07-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210719_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
    ]
