# Generated by Django 3.2.4 on 2021-07-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_teacher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
