# Generated by Django 3.2.4 on 2021-06-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_result_teacher_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty', verbose_name='Факультет'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='cathedras',
        ),
        migrations.AddField(
            model_name='teacher',
            name='cathedras',
            field=models.TextField(blank=True, null=True, verbose_name='Кафедры'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lessons',
            field=models.TextField(blank=True, null=True, verbose_name='Шо ведет'),
        ),
        migrations.DeleteModel(
            name='Cathedra',
        ),
    ]
