# Generated by Django 3.2.4 on 2021-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210630_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
