# Generated by Django 3.2.4 on 2021-08-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_teacher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherfacultyresult',
            name='message_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
