# Generated by Django 3.2.4 on 2021-09-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_teacherfacultyresult_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='votes_threshold',
            field=models.SmallIntegerField(default=10, verbose_name='Минимальное количество голосов для препода'),
        ),
    ]
