# Generated by Django 3.1.5 on 2021-01-27 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210127_0443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherngroup',
            options={'verbose_name': 'Препод+Группа', 'verbose_name_plural': 'Преподы+Группы'},
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='result',
            name='teacher_n_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacherngroup', verbose_name='Препод и группа'),
        ),
        migrations.AlterField(
            model_name='resultanswers',
            name='answer_1',
            field=models.PositiveSmallIntegerField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='resultanswers',
            name='answer_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Еще ответ'),
        ),
        migrations.AlterField(
            model_name='resultanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='teacherngroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='teacherngroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.teacher', verbose_name='Препод'),
        ),
    ]
