# Generated by Django 3.2.4 on 2021-10-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_faculty_votes_threshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherfacultyresult',
            options={'verbose_name': 'Результат препода на факультете'},
        ),
        migrations.AddField(
            model_name='teacherfacultyresult',
            name='teacher_type',
            field=models.CharField(choices=[('LECTOR', 'Лектор'), ('PRACTIC', 'Практик'), ('LECTOR_PRACTIC', 'Лектор и практик'), ('ENG', 'Английский')], default='KEK', max_length=20, verbose_name='Тип препода'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherfacultyresult',
            name='message_id',
            field=models.IntegerField(null=True),
        ),
    ]
