# Generated by Django 3.1.5 on 2021-01-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_faculty_poll_result_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultanswers',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
    ]
