# Generated by Django 3.1.5 on 2021-01-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20210128_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения'),
        ),
        migrations.AlterField(
            model_name='result',
            name='open_question_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ свободного микрофона'),
        ),
    ]
