# Generated by Django 3.1.5 on 2021-02-01 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210202_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='name_position',
        ),
    ]
