# Generated by Django 3.1.5 on 2021-02-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20210202_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name_position_short',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя+Должность сокращенно'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name_position',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя+Должность'),
        ),
    ]
