# Generated by Django 3.1.5 on 2021-02-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20210202_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='gavno', max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
