# Generated by Django 3.1.5 on 2021-02-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20210202_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя+Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name_position_short',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя+Должность сокращенно'),
        ),
    ]
