# Generated by Django 3.2 on 2021-06-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_auto_20210202_0412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='faculty',
        ),
        migrations.CreateModel(
            name='Cathedra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедри',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='cathedra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cathedra', verbose_name='Кафедра'),
        ),
    ]
